# Generated by Django 5.0.3 on 2024-04-01 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, help_text='Accepted file formats: Latex, doc, docx, odt, png, jpeg, gif, ps, eps, tif, tiff, pdf', null=True, upload_to='article_resources/')),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='starting_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='state',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Past', 'Past')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='honorsandawards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_pp.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='base.institution'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disclaimer', models.TextField(blank=True)),
                ('copyright', models.TextField(blank=True)),
                ('received_date', models.DateField(auto_now_add=True, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleUser', to=settings.AUTH_USER_MODEL)),
                ('article_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlestype', to='base.articletype')),
                ('institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_articles', to='base.institution')),
                ('keywords', models.ManyToManyField(blank=True, related_name='articles', to='base.keyword')),
                ('resources', models.ManyToManyField(blank=True, related_name='articles', to='base.resources')),
            ],
        ),
    ]
