# Generated by Django 5.0.3 on 2024-03-28 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institution_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='base.institution'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resources', models.FileField(blank=True, help_text='Accepted file formats: Latex, doc, docx, odt, png, jpeg, gif, ps, eps, tif, tiff, pdf', null=True, upload_to='article_resources/')),
                ('disclaimer', models.TextField(blank=True)),
                ('copyright', models.TextField(blank=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
                ('institutions', models.ManyToManyField(blank=True, related_name='articles', to='base.institution')),
                ('keywords', models.ManyToManyField(blank=True, related_name='articles', to='base.keyword')),
            ],
        ),
    ]
