# Generated by Django 5.0.3 on 2024-03-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_institution_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
