# Generated by Django 5.0.3 on 2024-04-02 08:19

import base.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_articletype_institution_keyword_resources_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.manager.UserManager()),
            ],
        ),
    ]
