# Generated by Django 5.0.3 on 2024-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Accepted file formats: Latex, doc, docx, odt, png, jpeg, gif, ps, eps, tif, tiff, pdf', null=True, upload_to='article_resources/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='resources',
        ),
        migrations.AddField(
            model_name='article',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='articles', to='base.resources'),
        ),
    ]
