# Generated by Django 5.0.3 on 2024-04-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_title_remove_user_user_title_user_orcid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.title'),
        ),
    ]
