# Generated by Django 5.0.3 on 2024-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_resources_remove_article_resources_article_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ManyToManyField(blank=True, related_name='articles', to='base.articletype'),
        ),
    ]
