# Generated by Django 5.0.3 on 2024-04-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_user_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_title',
            new_name='title',
        ),
    ]
