# Generated by Django 5.0.3 on 2024-03-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_article_article_type_article_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
    ]
