# Generated by Django 5.0.3 on 2024-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_user_title_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_or_institution_name', models.CharField(default='admin', max_length=250, verbose_name='owner_or_institution_name')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='base/culture_cover/', verbose_name='cover_image')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('link_to_orignal', models.URLField(max_length=1000, verbose_name='link_to_orignal')),
            ],
        ),
    ]
