# Generated by Django 5.0.3 on 2024-04-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name_of_researcher', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='searcher_videos')),
                ('thumbnail', models.ImageField(upload_to='searcher_thumb')),
            ],
        ),
    ]
