# Generated by Django 5.0.3 on 2024-03-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_article_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='institutions',
        ),
        migrations.AddField(
            model_name='article',
            name='institution',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution_articles', to='base.institution'),
            preserve_default=False,
        ),
    ]
