# Generated by Django 5.0.3 on 2024-04-17 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_searcher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcher',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
