# Generated by Django 5.0.3 on 2024-04-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_searcher_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcher',
            name='video',
            field=models.URLField(default='https://www.youtube.com/watch?v=oEtOT6n-17o'),
        ),
    ]
