# Generated by Django 5.0.3 on 2024-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
