# Generated by Django 5.0.3 on 2024-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_searcher_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcher',
            name='video',
            field=models.URLField(default='https://www.youtube.com/', help_text='Please Upload your Video on Youtube and Paste Link here...'),
        ),
    ]
