# Generated by Django 5.0.3 on 2024-03-29 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_resources_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articleUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
