# Generated by Django 5.0.3 on 2024-04-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_searcher_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searcher',
            old_name='video',
            new_name='video_url',
        ),
    ]
