# Generated by Django 5.0.3 on 2024-03-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_article_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
