# Generated by Django 5.0.3 on 2024-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_user_facebook_link_alter_user_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_pp.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
