# Generated by Django 5.0.3 on 2024-03-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_short_description_expertise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='honorsandawards',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='user',
        ),
    ]
