# Generated by Django 5.0.3 on 2024-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_affiliation_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='honorsandawards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
