# Generated by Django 5.0.3 on 2024-04-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
